[package]
name = "basic"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
cassandra-cpp = "0.17.0"
tokio = { version = "1.1.0", features = ["full"] }
getopts = "0.2.12"
anyhow = "1.0.40"
num_cpus = "1.0"

[profile.release]
lto = true